---
- name: Copy file from JFrog Artifactory to Windows server
  hosts: windows
  gather_facts: no
  tasks:
    - name: Download file from JFrog Artifactory to Windows server
      win_get_url:
        url: "{{ jfrog_url }}"
        dest: "{{ dest_path }}"
        url_username: "{{ jfrog_user | default(omit) }}"
        url_password: "{{ jfrog_password | default(omit) }}"
        validate_certs: yes
      no_log: "{{ jfrog_user is defined and jfrog_password is defined }}"
